blank_issues_enabled: false
contact_links:
  - name: Start Your Lab Manual Template
    url: https://github.com/startyourlab/manual/issues/new/choose
    about: Please ask and answer questions about the lab manual template here.
    
